# Generated by Django 6.0.2 on 2026-03-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
