# Generated by Django 6.0.2 on 2026-03-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_donorprofile_address_alter_donorprofile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, null=True),
        ),
    ]
