# Generated by Django 6.0.2 on 2026-03-10 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_donorprofile_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='is_premium',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
