# Generated by Django 6.0.2 on 2026-03-02 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DonationResponse',
        ),
    ]
